### PR TITLE
Trade executor tests

### PR DESCRIPTION
**Pull request by SaralynOgden**

### CODE REVIEW

**Review by bpsix — APPROVED** [review]
Thoughts on eventually cleaning up our file structure? Most of our code can be combined into files of related data

**Comment by SaralynOgden** [comment]
> Thoughts on eventually cleaning up our file structure? Most of our code can be combined into files of related data

Right. That will be my next PR. I keep saying that, but this time I mean it :D

**Review by BensGitHub2022 — CHANGES_REQUESTED** [review]
Hey! Sorry, I only had time to review this in earnest just now. I was studying for my midterm most of the week. 

This PR has a lot of things in it - 
1. Can you put renaming in its own PR? Please don't combine renaming with other changes it makes it hard to review. You could do rename and organize as one PR based on what we talked about: renaming - I agree with your naming conventions to make class names match module names and organization - I remember where we landed was making separate folders for mt5 & sim classes. This would get approved on my end and everyone could have a fresh PR to merge with their branch and continue working!
2. Can tests have their own PR as well? I think the more unit tests we have the better. These changes would get approved as well.
3. Can making signals class have its own PR? I wanted to review this one more and it was hard to track when it was mixed in with the other changes.

**Comment by SaralynOgden** [comment]
> Can you put renaming in its own PR?

It looks like I only have one renaming here which was likely a merge conflict mistake since it's renaming trade_executor_factory back to trade_execution_factory. There's no need for this and I'll keep it the way it is.

**Comment by SaralynOgden** [comment]
> Can tests have their own PR as well?
> Can making signals class have its own PR?

These will need to go in sequentially since the tests rely upon the signals class being created.

**Comment by SaralynOgden** [comment]
Closing to break apart into two PRs

**Pull request closed without merging**
